Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.communicator = "ssh"

  nodes = {
    "sd0" => { cpus: 2, ram: 4096, maxram: 8192, role: "master", switch: "sd-ext-vswitch" },
    "sd1" => { cpus: 2, ram: 4096, maxram: 12288, role: "worker", switch: "sd-ext-vswitch" },
    "sd2" => { cpus: 2, ram: 4096, maxram: 12288, role: "worker", switch: "sd-ext-vswitch" },
    "sd3" => { cpus: 2, ram: 4096, maxram: 12288, role: "worker", switch: "sd-ext-vswitch" }
  }

  nodes.each do |name, opts|
    config.vm.define name do |node|
      node.vm.hostname = name

      node.vm.provider "hyperv" do |hv|
        hv.memory = opts[:ram]
        hv.maxmemory = opts[:maxram]
        hv.cpus = opts[:cpus]
        hv.vm_integration_services = {
          guest_service_interface: true
        }
        hv.linked_clone = true
        hv.enable_virtualization_extensions = true
        hv.vmname = name
        # Remove network_adapters (unsupported)
      end

      # Attach external vSwitch for sd0
      # if name == "sd0"
      node.vm.network "public_network", bridge: opts[:switch]
      # end

      # Worker nodes will have sd-int-vswitch added manually

      node.vm.synced_folder "secrets", "/vagrant/secrets", type: "smb", create: true

      script = opts[:role] == "master" ? "provision-master.sh" : "provision-worker.sh"
      node.vm.provision "shell", path: "scripts/#{script}"
    end
  end
end