#cloud-config
package_update: true
package_upgrade: true
packages:
  - postgresql
  - postgresql-contrib

write_files:
  - path: /tmp/set-postgres-password.sh
    permissions: '0700'
    content: |
      #!/bin/bash
      sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '${POSTGRES_PASSWORD}';"

runcmd:
  - sed -i "s/^#listen_addresses =.*/listen_addresses = '*'/g" /etc/postgresql/*/main/postgresql.conf
  - echo "host all all 0.0.0.0/0 md5" >> /etc/postgresql/*/main/pg_hba.conf
  - chmod +x /tmp/set-postgres-password.sh
  - POSTGRES_PASSWORD='__REPLACE__PASSWORD__' /tmp/set-postgres-password.sh
  - systemctl restart postgresql
